### PR TITLE
Add Channel Up / Down, Channel Change, Use Proper On / Off States

### PR DESCRIPTION
**Pull request by jaruba**
I added support for channel up / down, changing channels and using proper `On` / `Off` states based on HA constants (the smartthings api gives "off" and "on", while HA uses "Off" and "On")

### CODE REVIEW

**Comment by jaruba** [comment]
Also added a commit to set `media_title` properly, previously I made a PR that would reply with the `media_title` as `state`, I since learned this is a mistake.

`state` should only be On / Off, `media_title` should report the channel ID / input source / etc.

**Comment by PiotrMachowski** [comment]
You can also easily add Play/Pause support by returning correct states (See: #3)

**Comment by jaruba** [comment]
@PiotrMachowski No time to do that now tbh, I did this PR before my work hours started. I'm also not sure when the play/pause states ever get used? do they get used in apps too? or with live tv? or does it just show when someone is playing a stream on the TV? (through UPnP / DLNA)

Probably just the last one?

**Comment by PiotrMachowski** [comment]
@jaruba I don't know where it is supported, as I don't have a Samsung TV, but a soundbar. I assume that it is supported whenever you can use play/pause on the remote (on my LG it works for apps as well, e.g. Spotify, Netflix).

**Comment by pegatron89** [comment]
Thanks for this guys, I have merged and updated with stop play pause. It works on apps i have tested - plex, netflix. I manually set state._playing so should be fine.

**Pull request merged**
